package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.DotCoverBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.DotnetTestStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dotCover
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetTest
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        dotnetTest {
            id = "dotnet"
            projects = "money/Money.csproj"
            sdk = "6"
            coverage = dotcover {
                toolPath = "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%"
            }
        }
        dotnetTest {
            id = "dotnet_1"
            projects = "syntax/AssertSyntax.csproj"
            sdk = "6"
            coverage = dotcover {
                toolPath = "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%"
            }
        }
        dotCover {
            name = "Merge snapshots from the previous build steps + add one"
            id = "Merge_snapshots_from_the_previous_build_steps_add_one"
            toolPath = "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%"
            executable = "/usr/bin/dotnet"
            commandLineArguments = """test %teamcity.build.checkoutDir%\DataDrivenTests\DataDrivenTests.csproj"""
            dockerImage = "mcr.microsoft.com/dotnet/sdk:6.0"
            dockerImagePlatform = DotCoverBuildStep.ImagePlatform.Linux
            dockerPull = true
        }
        script {
            name = "Echo parameters"
            id = "Echo_parameters"
            scriptContent = "echo %root_text% >> text.txt"
        }
        script {
            name = "Echo parameter"
            id = "Echo_parameter"
            scriptContent = "echo %root_text% >> text.txt"
        }
    }
    steps {
        update<DotnetTestStep>(1) {
            clearConditions()
            param("dotNetCoverage.tool", "")
        }
    }
}
